odometry_ekf:
  ros__parameters:
    use_imu_orientation: true
    use_imu_yaw_rate: true

    output_frame: "odom"
    output_child_frame: "base_footprint_ekf"

    min_variance: 1.0e-9
    unused_pose_variance: 1000000.0
    unused_twist_variance: 1000000.0

    imu_yaw_variance_override: 0.05
    imu_yaw_rate_variance_override: 1.0e-5

    process_noise_x: 0.02
    process_noise_y: 0.02
    process_noise_yaw: 0.01
    process_noise_v: 0.05
    process_noise_omega: 0.05
