wheel_odometry_parametric:
  ros__parameters:
    left_wheel_radius: 0.032
    right_wheel_radius: 0.034
    wheel_separation: 0.18
    com_y_offset: 0.0

    left_wheel_radius_stddev: 0.002
    right_wheel_radius_stddev: 0.002
    wheel_separation_stddev: 0.003
    com_y_offset_stddev: 0.001

    left_encoder_position_stddev: 0.0024
    right_encoder_position_stddev: 0.0022

    unused_pose_variance: 1000000.0
    unused_twist_variance: 1000000.0
