import argparse
from pathlib import Path

import sympy as sp


def build_pairwise_energy_poly():
    # Optimizer variables:
    # u = [tx, ty, tz, r0, r1, r2, r3, r4, r5, r6, r7, r8]
    tx, ty, tz = sp.symbols("tx ty tz", real=True)
    t = sp.Matrix([tx, ty, tz])

    r0, r1, r2, r3, r4, r5, r6, r7, r8 = sp.symbols(
        "r0 r1 r2 r3 r4 r5 r6 r7 r8", real=True
    )

    R = sp.Matrix([
        [r0, r1, r2],
        [r3, r4, r5],
        [r6, r7, r8],
    ])

    Xx, Xy, Xz = sp.symbols("Xx Xy Xz", real=True)
    X = sp.Matrix([Xx, Xy, Xz])

    Yx, Yy, Yz = sp.symbols("Yx Yy Yz", real=True)
    Y = sp.Matrix([Yx, Yy, Yz])

    Xisxx, Xisxy, Xisxz, Xisyy, Xisyz, Xiszz = sp.symbols(
        "Xisxx Xisxy Xisxz Xisyy Xisyz Xiszz", real=True
    )
    iSX = sp.Matrix([
        [Xisxx, Xisxy, Xisxz],
        [Xisxy, Xisyy, Xisyz],
        [Xisxz, Xisyz, Xiszz],
    ])

    Yisxx, Yisxy, Yisxz, Yisyy, Yisyz, Yiszz = sp.symbols(
        "Yisxx Yisxy Yisxz Yisyy Yisyz Yiszz", real=True
    )
    iSY = sp.Matrix([
        [Yisxx, Yisxy, Yisxz],
        [Yisxy, Yisyy, Yisyz],
        [Yisxz, Yisyz, Yiszz],
    ])

    d = (R * Y + t) - X
    C_ij = sp.symbols("C_ij", real=True)

    L_ij = sp.expand(C_ij * (d.T * (iSX + R * iSY * R.T) * d)[0])

    opt_vars = [
        tx, ty, tz,
        r0, r1, r2,
        r3, r4, r5,
        r6, r7, r8,
    ]

    poly = sp.Poly(sp.expand(L_ij / C_ij), *opt_vars)
    return poly, opt_vars


def u_power_name(var_idx: int, exponent: int) -> str:
    if exponent == 0:
        return "1.0f"
    if exponent == 1:
        return f"u{var_idx}"
    return f"u{var_idx}_{exponent}"


def monomial_expr(exponents) -> str:
    factors = [
        u_power_name(var_idx, exponent)
        for var_idx, exponent in enumerate(exponents)
        if exponent != 0
    ]

    if not factors:
        return "1.0f"

    return " * ".join(factors)


def derivative_monomial_expr(exponents, deriv_var_idx: int) -> str:
    deriv_exp = exponents[deriv_var_idx]

    if deriv_exp == 0:
        return "0.0f"

    factors = [str(deriv_exp) + ".0f"]

    for var_idx, exponent in enumerate(exponents):
        if var_idx == deriv_var_idx:
            exponent -= 1

        if exponent != 0:
            factors.append(u_power_name(var_idx, exponent))

    return " * ".join(factors)


def emit_u_power_precompute(f, variable_order, max_exp):
    for var_idx, name in enumerate(variable_order):
        f.write(f"    const float u{var_idx} = u[{var_idx}]; // {name}\n")

    f.write("\n")

    for var_idx in range(len(variable_order)):
        for exponent in range(2, max_exp + 1):
            prev = f"u{var_idx}" if exponent == 2 else f"u{var_idx}_{exponent - 1}"
            f.write(
                f"    const float u{var_idx}_{exponent} = "
                f"{prev} * u{var_idx};\n"
            )

    f.write("\n")


def emit_b_inl(out_path: Path):
    poly, opt_vars = build_pairwise_energy_poly()

    variable_order = [str(v) for v in opt_vars]
    basis_exponents = poly.monoms()
    basis_size = len(basis_exponents)
    total_degree = poly.total_degree()
    max_exp = max(max(row) for row in basis_exponents)

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Generated by generate_B_inl.py\n")
        f.write("// Do not edit by hand.\n")
        f.write("//\n")
        f.write("// Computes the monomial basis B(u) used by:\n")
        f.write("//     L(u) = A^T B(u)\n")
        f.write("//\n")
        f.write("// Variable order:\n")
        for idx, name in enumerate(variable_order):
            f.write(f"//     u[{idx}] = {name}\n")
        f.write("//\n")
        f.write(f"// Basis size: {basis_size}\n")
        f.write(f"// Total degree: {total_degree}\n\n")

        f.write("#pragma once\n\n")

        f.write("inline void computeBasisB(\n")
        f.write("    const std::array<float, 12>& u,\n")
        f.write(f"    std::array<float, {basis_size}>& B\n")
        f.write(")\n")
        f.write("{\n")

        emit_u_power_precompute(f, variable_order, max_exp)

        for k, exponents in enumerate(basis_exponents):
            f.write(f"    // k = {k}, exponents = {list(exponents)}\n")
            f.write(f"    B[{k}] = {monomial_expr(exponents)};\n")

        f.write("}\n\n")

        f.write("inline float computeEnergyFromBasis(\n")
        f.write("    const BasisCoeffsVec& A,\n")
        f.write(f"    const std::array<float, {basis_size}>& B\n")
        f.write(")\n")
        f.write("{\n")
        f.write("    float energy = 0.0f;\n\n")
        f.write(f"    for(int k = 0; k < {basis_size}; ++k)\n")
        f.write("    {\n")
        f.write("        energy += A.vals[k] * B[k];\n")
        f.write("    }\n\n")
        f.write("    return energy;\n")
        f.write("}\n\n")

        f.write("inline void computeEnergyAndEuclideanGradient(\n")
        f.write("    const std::array<float, 12>& u,\n")
        f.write("    const BasisCoeffsVec& A,\n")
        f.write("    float& energy,\n")
        f.write("    std::array<float, 12>& grad_u\n")
        f.write(")\n")
        f.write("{\n")

        emit_u_power_precompute(f, variable_order, max_exp)

        f.write("    energy = 0.0f;\n")
        f.write("    grad_u.fill(0.0f);\n\n")

        for k, exponents in enumerate(basis_exponents):
            b_expr = monomial_expr(exponents)

            f.write(f"    // k = {k}, exponents = {list(exponents)}\n")
            f.write(f"    const float A{k} = A.vals[{k}];\n")
            f.write(f"    const float B{k} = {b_expr};\n")
            f.write(f"    energy += A{k} * B{k};\n")

            for p, exponent in enumerate(exponents):
                if exponent == 0:
                    continue

                d_expr = derivative_monomial_expr(exponents, p)
                f.write(f"    grad_u[{p}] += A{k} * ({d_expr});\n")

            f.write("\n")

        f.write("}\n")

    print(f"Wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate inline C++ code for B(u), the polynomial monomial basis."
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output .inl path. Defaults to bot_dugma/src/generated/B.inl.",
    )

    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    bot_dugma_root = script_dir.parent

    out_path = args.out
    if out_path is None:
        out_path = bot_dugma_root / "src" / "generated" / "B.inl"

    emit_b_inl(out_path)


if __name__ == "__main__":
    main()
