import sympy as sp
from pathlib import Path
import argparse
import re


def expand_small_integer_powers(expr):
    def _pow_to_mul(node):
        if isinstance(node, sp.Pow):
            base, exp = node.as_base_exp()
            if exp.is_Integer and int(exp) >= 2:
                n = int(exp)
                return sp.Mul(*([base] * n), evaluate=False)
        return node

    return expr.replace(
        lambda e: isinstance(e, sp.Pow) and e.exp.is_Integer and int(e.exp) >= 2,
        _pow_to_mul,
    )


def cxxcode_no_pow(expr):
    code = sp.cxxcode(expand_small_integer_powers(expr))

    def repl(match):
        base = match.group(1)
        power = int(match.group(2))
        return "(" + "*".join([base] * power) + ")"

    code = re.sub(
        r"std::pow\(([A-Za-z_][A-Za-z0-9_]*), ([2-4])\)",
        repl,
        code,
    )

    return code


def build_pairwise_energy_poly():
    # Params to optimize over
    # translation increment 
    tx, ty, tz = sp.symbols("tx ty tz", real=True)
    t = sp.Matrix([tx, ty, tz])

    # rotation increment
    r0, r1, r2, r3, r4, r5, r6, r7, r8 = sp.symbols(
        "r0 r1 r2 r3 r4 r5 r6 r7 r8", real=True
    )

    R = sp.Matrix([
        [r0, r1, r2],
        [r3, r4, r5],
        [r6, r7, r8],
    ])


    # some point x_i in point cloud X_curr
    Xx, Xy, Xz = sp.symbols("Xx Xy Xz", real=True)
    X = sp.Matrix([Xx, Xy, Xz])

    # some point y_j in point cloud Y_curr
    Yx, Yy, Yz = sp.symbols("Yx Yy Yz", real=True)
    Y = sp.Matrix([Yx, Yy, Yz])

    # inverse covaraince elements of x_i
    Xisxx, Xisxy, Xisxz, Xisyy, Xisyz, Xiszz = sp.symbols(
        "Xisxx Xisxy Xisxz Xisyy Xisyz Xiszz", real=True
        )
    iSX = sp.Matrix([
        [Xisxx, Xisxy, Xisxz],
        [Xisxy, Xisyy, Xisyz],
        [Xisxz, Xisyz, Xiszz]
    ])

    # inverse covaraince elements of y_j
    Yisxx, Yisxy, Yisxz, Yisyy, Yisyz, Yiszz = sp.symbols(
        "Yisxx Yisxy Yisxz Yisyy Yisyz Yiszz", real=True
        )
    iSY = sp.Matrix([
        [Yisxx, Yisxy, Yisxz],
        [Yisxy, Yisyy, Yisyz],
        [Yisxz, Yisyz, Yiszz]
    ])

    # Euclidiean distance
    d = (R*Y + t) - X

    # C_ij_old
    C_ij = sp.symbols("C_ij", real=True)

    # Pairwise energy
    L_ij = sp.expand(C_ij * (d.T * (iSX + R*iSY*R.T) * d)[0])

    opt_vars = [
        tx, ty, tz,
        r0, r1, r2,
        r3, r4, r5,
        r6, r7, r8,
    ]

    return sp.Poly(sp.expand(L_ij / C_ij), *opt_vars)


def emit_g_tile_inl(k_tile: int, out_path: Path):
    
    if k_tile <= 0:
        raise ValueError("k_tile must be positive")
    
    poly = build_pairwise_energy_poly()
    coeffs = poly.coeffs()

    basis_size = len(coeffs)
    if basis_size % k_tile != 0:
        print(
            f"Warning: basis_size={basis_size} is not divisible by k_tile={k_tile}; "
            "the final tile will be partial."
        )

    num_tiles = (basis_size + k_tile - 1) // k_tile
    function_name = f"accumulateGTileK{k_tile}"

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Generated by generate_G_K_tile_inl.py\n")
        f.write("// Do not edit by hand.\n")
        f.write(f"// Basis size: {basis_size}\n")
        f.write(f"// K_tile: {k_tile}\n")
        f.write(f"// Number of K tiles: {num_tiles}\n\n")

        f.write("#pragma once\n\n")

        f.write("__device__ __forceinline__\n")
        f.write(f"void {function_name}(\n")
        f.write("    int k_tile_id,\n")
        f.write("    float Xx, float Xy, float Xz,\n")
        f.write("    float Yx, float Yy, float Yz,\n")
        f.write("    float Xisxx, float Xisxy, float Xisxz,\n")
        f.write("    float Xisyy, float Xisyz, float Xiszz,\n")
        f.write("    float Yisxx, float Yisxy, float Yisxz,\n")
        f.write("    float Yisyy, float Yisyz, float Yiszz,\n")
        f.write("    float C,\n")
        f.write("    float* A_thread\n")
        f.write(")\n")
        f.write("{\n")
        f.write("    switch (k_tile_id)\n")
        f.write("    {\n")

        for tile_id in range(num_tiles):
            k0 = tile_id * k_tile
            tile_coeffs = coeffs[k0:k0 + k_tile]

            repls, reduced = sp.cse(tile_coeffs)

            f.write(f"    case {tile_id}:\n")
            f.write("    {\n")
            f.write(f"        // Global k range: {k0}..{k0 + len(tile_coeffs) - 1}\n")

            for sym, rhs in repls:
                f.write(f"        const float {sym} = {cxxcode_no_pow(rhs)};\n")

            for local_k, expr in enumerate(reduced):
                global_k = k0 + local_k
                f.write(
                    f"        // k = {global_k}\n"
                    f"        A_thread[{local_k}] += C * ({cxxcode_no_pow(expr)});\n"
                )

            f.write("        break;\n")
            f.write("    }\n\n")

        f.write("    default:\n")
        f.write("        break;\n")
        f.write("    }\n")
        f.write("}\n")

    print(f"Wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate CUDA inline G_k tile accumulator."
    )
    parser.add_argument(
        "--k-tile",
        type=int,
        default=7,
        help="Number of G coefficients computed per K tile.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output .inl path. Defaults to bot_dugma/src/generated/G_K_tile_<k>.inl",
    )

    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    bot_dugma_root = script_dir.parent

    out_path = args.out
    if out_path is None:
        out_path = bot_dugma_root / "src" / "generated" / f"G_K_tile_{args.k_tile}.inl"

    emit_g_tile_inl(args.k_tile, out_path)


if __name__ == "__main__":
    main()
