import sympy as sp
from pathlib import Path

qx, qy, qz, qw = sp.symbols("qx qy qz qw", real=True)

R_q = sp.Matrix([
    [1 - 2*(qy**2 + qz**2),     2*(qx*qy - qw*qz),     2*(qx*qz + qw*qy)],
    [    2*(qx*qy + qw*qz), 1 - 2*(qx**2 + qz**2),     2*(qy*qz - qw*qx)],
    [    2*(qx*qz - qw*qy),     2*(qy*qz + qw*qx), 1 - 2*(qx**2 + qy**2)],
])

g0, g1, g2, g3, g4, g5, g6, g7, g8 = sp.symbols(
    "g0 g1 g2 g3 g4 g5 g6 g7 g8",
    real=True
)

Grad_r = sp.Matrix([
    [g0, g1, g2],
    [g3, g4, g5],
    [g6, g7, g8],
])

q = [qx, qy, qz, qw]

Grad_q = []

for q_elem in q:
    expr = sp.Integer(0)

    for i in range(3):
        for j in range(3):
            expr += Grad_r[i, j] * sp.diff(R_q[i, j], q_elem)

    Grad_q.append(sp.simplify(expr))

for name, expr in zip(["qx", "qy", "qz", "qw"], Grad_q):
    print(f"dL/d{name} =")
    print(sp.cxxcode(expr))
    print()


out_path = Path("bot_dugma/src/generated/grad_r_to_grad_q.inl")

with out_path.open("w", encoding="utf-8") as f:
    f.write("// Generated by bot_dugma/m_step_opt/R_to_q_derivative.py\n")
    f.write("// Converts dL/dR_flat to dL/dq for unit quaternion q = [qx, qy, qz, qw].\n")
    f.write("// R_flat/grad_R_flat are row-major: [R00, R01, R02, R10, ..., R22].\n\n")

    f.write("inline void GradRFlatToGradQ(\n")
    f.write("    const float qx,\n")
    f.write("    const float qy,\n")
    f.write("    const float qz,\n")
    f.write("    const float qw,\n")
    f.write("    const float* grad_R_flat,\n")
    f.write("    float* grad_q\n")
    f.write(")\n")
    f.write("{\n")

    for idx in range(9):
        f.write(f"    const float g{idx} = grad_R_flat[{idx}];\n")

    f.write("\n")

    for idx, expr in enumerate(Grad_q):
        f.write(f"    grad_q[{idx}] = {sp.cxxcode(expr)};\n")

    f.write("}\n")

print(f"Wrote generated include to: {out_path}")